maxSurge: 25%
maxUnavailable: 25%
containerRepo: 221416552528.dkr.ecr.us-east-1.amazonaws.com/illuminati-react-frontend
buildVersion: 1.0.30
cpuRequests: 100m
memoryRequests: 128Mi
cpuLimit: 200m
memorylimit: 256Mi
healthPath: /
containerPort: 80
minReplicas: 1
maxReplicas: 20
cpuAverageUtilization: 70
memoryAverageUtilization: 70
