apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: illuminati
  labels:
    run: frontend
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        run: frontend
        version: "1"
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: frontend
      imagePullSecrets:
        - name: ecr-frontend
      containers:
        - name: frontend
          image: {{ .Values.containerRepo }}:{{ .Values.buildVersion }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.cpuRequests | quote }}
              memory: {{ .Values.memoryRequests | quote }}
            limits:
              cpu: {{ .Values.cpuLimit | quote }}
              memory: {{ .Values.memorylimit | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
