apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: illuminati
  labels:
    run: frontend
spec:
  type: ClusterIP  
  selector:
    run: frontend
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}  
      protocol: TCP
